<?php

namespace ContainerFx3p2f7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RRFjc5bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RRFjc5b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RRFjc5b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'conference' => ['privates', '.errored..service_locator.RRFjc5b.App\\Entity\\Conference', NULL, 'Cannot autowire service ".service_locator.RRFjc5b": it needs an instance of "App\\Entity\\Conference" but this type has been excluded in "config/services.yaml".'],
            'conferenceRepository' => ['privates', 'App\\Repository\\ConferenceRepository', 'getConferenceRepositoryService', false],
            'photoDir' => ['privates', '.value.H8rOLf3', 'get_Value_H8rOLf3Service', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'conference' => 'App\\Entity\\Conference',
            'conferenceRepository' => 'App\\Repository\\ConferenceRepository',
            'photoDir' => '?',
        ]);
    }
}
