<?php

namespace ContainerFx3p2f7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConferenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RRFjc5b.App\Entity\Conference' shared service.
     *
     * @return \App\Entity\Conference
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RRFjc5b": it needs an instance of "App\\Entity\\Conference" but this type has been excluded in "config/services.yaml".');
    }
}
