<?php

namespace ContainerFx3p2f7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConferenceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConferenceController' shared autowired service.
     *
     * @return \App\Controller\ConferenceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConferenceController.php';

        $container->services['App\\Controller\\ConferenceController'] = $instance = new \App\Controller\ConferenceController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ConferenceController', $container));

        return $instance;
    }
}
