<?php

namespace ContainerZ85PbsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_H8rOLf3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.H8rOLf3' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.H8rOLf3'] = (\dirname(__DIR__, 4).'/public/uploads/photos');
    }
}
