<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAH7tYRI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAH7tYRI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAH7tYRI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAH7tYRI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAH7tYRI\App_KernelDevDebugContainer([
    'container.build_hash' => 'AH7tYRI',
    'container.build_id' => '1e831b9b',
    'container.build_time' => 1731416688,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAH7tYRI');
