<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBgRUtZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBgRUtZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFBgRUtZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFBgRUtZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFBgRUtZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FBgRUtZ',
    'container.build_id' => '4bb732e7',
    'container.build_time' => 1731583424,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBgRUtZ');
