<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDHxhoDF\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDHxhoDF/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerDHxhoDF.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerDHxhoDF\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerDHxhoDF\App_KernelDevContainer([
    'container.build_hash' => 'DHxhoDF',
    'container.build_id' => '1940ba9b',
    'container.build_time' => 1731414881,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDHxhoDF');
